import { createRequire } from 'module';
import fs from 'fs';
import path from 'path';

const RESTRICTED_MARKER = "can't be called in restricted-execution mode";
const DANGEROUS_NAMES = new Set(['constructor', '__proto__', 'prototype', 'dimension']);
const METHOD_RE = /^\s+(?:static\s+|readonly\s+|get\s+|set\s+)*([A-Za-z_]\w*)\s*(?:<.+>)?\s*\(/;
const OUTPUT_RELATIVE = 'scripts/src/classes/analyzearea/readOnlyMethods.js';

function loadServerDts() {
    const require = createRequire(import.meta.url);
    const pkgPath = require.resolve('@minecraft/server/package.json');
    const version = JSON.parse(fs.readFileSync(pkgPath, 'utf8')).version;
    const dts = fs.readFileSync(path.join(path.dirname(pkgPath), 'index.d.ts'), 'utf8');
    return { dts, version };
}

function parseReadOnlyMethods(dts) {
    const allNames = new Set();
    const forbidden = new Set();
    let inComment = false;
    let doc = '';
    for (const line of dts.split('\n')) {
        const trimmed = line.trim();
        if (inComment) {
            doc += `${line}\n`;
            if (trimmed.includes('*/')) inComment = false;
            continue;
        }
        if (trimmed.startsWith('/*')) {
            doc = `${line}\n`;
            inComment = !trimmed.includes('*/');
            continue;
        }
        if (trimmed.startsWith('*') || trimmed.startsWith('//')) continue;
        const match = METHOD_RE.exec(line);
        if (match) {
            allNames.add(match[1]);
            if (doc.includes(RESTRICTED_MARKER)) forbidden.add(match[1]);
        }
        if (trimmed.length > 0) doc = '';
    }
    return [...allNames].filter((name) => !forbidden.has(name) && !DANGEROUS_NAMES.has(name)).sort();
}

function formatFile(methods, version) {
    const list = methods.map((name) => `    '${name}'`).join(',\n');
    return `// AUTO-GENERATED by filters/generate_readonly_methods. Do not edit by hand.\n`
        + `// Source: @minecraft/server@${version}\n`
        + `export const readOnlyMethods = new Set([\n${list}\n]);\n`;
}

function main() {
    const { dts, version } = loadServerDts();
    const methods = parseReadOnlyMethods(dts);
    const bpRoot = fs.existsSync('BP') ? 'BP' : 'Canopy[BP]';
    const target = path.join(bpRoot, OUTPUT_RELATIVE);
    fs.writeFileSync(target, formatFile(methods, version), 'utf8');
    console.log(`[generate-readonly-methods] Wrote ${methods.length} read-only method names from @minecraft/server@${version} to ${target}`);
}

main();
