export const categoryToMobMap = {
    'animal' : [
        'armadillo',
        'bee',
        'camel',
        'chicken',
        'cow',
        'dolphin',
        'donkey',
        'fox',
        'frog',
        'glow_squid',
        'goat',
        'hoglin',
        'horse',
        'llama',
        'mooshroom',
        'ocelot',
        'panda',
        'parrot',
        'pig',
        'polar_bear',
        'rabbit',
        'sheep',
        'squid',
        'strider',
        'turtle',
        'wolf'
    ],
    'ambient' : [ 'bat' ],
    'cat' : [ 'cat' ],
    'monster' : [
        'blaze',
        'bogged',
        'creeper',
        'drowned',
        'enderman',
        'ghast',
        'guardian',
        'husk',
        'magma_cube',
        'phantom',
        'piglin',
        'skeleton',
        'slime',
        'spider',
        'stray',
        'witch',
        'wither_skeleton',
        'zombie_pigman',
        'zombie'
    ],
    'pillager' : [
        'pillager'
    ],
    'water_animal' : [
        'axolotl',
        'pufferfish',
        'salmon',
        'tropicalfish'
    ],
    'none' : [
        'allay',
        'breeze',
        'cave_spider',
        'copper_golem',
        'creaking',
        'elder_guardian',
        'ender_dragon',
        'endermite',
        'evocation_illager',
        'fish',
        'happy_ghast',
        'iron_golem',
        'lightning_bolt',
        'llama_spit',
        'mule',
        'npc',
        'piglin_brute',
        'player',
        'ravager',
        'shulker',
        'silverfish',
        'skeleton_horse',
        'sniffer',
        'snow_golem',
        'tadpole',
        'trader_llama',
        'vex',
        'villager',
        'villager_v2',
        'vindicator',
        'wandering_trader',
        'warden',
        'wither',
        'zoglin',
        'zombie_horse',
        'zombie_villager',
        'zombie_villager_v2'
    ]
}

export const intToBiomeMap = {
    0: 'Bamboo Jungle',
    1: 'Bamboo Jungle Hills',
    2: 'Basalt Deltas',
    3: 'Beach',
    4: 'Birch Forest',
    5: 'Birch Forest Hills',
    6: 'Birch Forest Hills M',
    7: 'Birch Forest (Old Growth)',
    8: 'Cherry Grove',
    9: 'Cold Beach',
    10: 'Cold Ocean',
    11: 'Cold Taiga',
    12: 'Cold Taiga Hills',
    13: 'Cold Taiga M',
    14: 'Crimson Forest',
    15: 'Deep Cold Ocean',
    16: 'Deep Dark',
    17: 'Deep Frozen Ocean',
    18: 'Deep Lukewarm Ocean',
    19: 'Deep Ocean',
    20: 'Deep Warm Ocean',
    21: 'Desert',
    22: 'Desert Hills',
    23: 'Desert M',
    24: 'Dripstone Caves',
    25: 'Windswept Hills',
    26: 'Windswept Hills Edge',
    27: 'Windswept Hills (Gravelly)',
    28: 'Windswept Forest',
    29: 'Windswept Forest M',
    30: 'Flower Forest',
    31: 'Forest',
    32: 'Forest Hills',
    33: 'Frozen Ocean',
    34: 'Frozen Peaks',
    35: 'Frozen River',
    36: 'Grove',
    37: 'Hell',
    38: 'Snowy Mountains',
    39: 'Snowy Plains',
    40: 'Ice Spikes',
    41: 'Jagged Peaks',
    42: 'Jungle',
    43: 'Jungle Edge',
    44: 'Jungle Edge M',
    45: 'Jungle Hills',
    46: 'Jungle M',
    47: 'Legacy Frozen Ocean',
    48: 'Lukewarm Ocean',
    49: 'Lush Caves',
    50: 'Mangrove Swamp',
    51: 'Meadow',
    52: 'Mega Taiga',
    53: 'Mega Taiga Hills',
    54: 'Badlands',
    55: 'Badlands (Eroded)',
    56: 'Badlands Plateau',
    57: 'Badlands Plateau M',
    58: 'Badlands (Wooded)',
    59: 'Badlands (Wooded) M',
    60: 'Mushroom Island',
    61: 'Mushroom Island Shore',
    62: 'Ocean',
    63: 'Plains',
    64: 'Redwood Taiga Hills M',
    65: 'Redwood Taiga M',
    66: 'River',
    67: 'Roofed Forest',
    68: 'Roofed Forest M',
    69: 'Savanna',
    70: 'Savanna (Windswept)',
    71: 'Savanna Plateau',
    72: 'Savanna Plateau M',
    73: 'Snowy Slopes',
    74: 'Soulsand Valley',
    75: 'Stone Beach',
    76: 'Stony Peaks',
    77: 'Sunflower Plains',
    78: 'Swampland',
    79: 'Swampland M',
    80: 'Taiga',
    81: 'Taiga Hills',
    82: 'Taiga M',
    83: 'The End',
    84: 'Warm Ocean',
    85: 'Warped Forest',
    86: 'Pale Garden'
};

export const biomeToHexColorMap = {
    "Bamboo Jungle": '#768E14',
    "Bamboo Jungle Hills": '#3B470A',
    "Basalt Deltas": '#403636',
    "Beach": '#FADE55',
    "Birch Forest": '#307444',
    "Birch Forest Hills": '#1F5F32',
    "Birch Forest Hills M": void 0,
    "Birch Forest (Old Growth)": '#5a9c6d',
    "Cherry Grove": '#f6b9dc',
    "Cold Beach": '#faf0c2',
    "Cold Ocean": '#202070',
    "Cold Taiga": '#32554a',
    "Cold Taiga Hills": '#253f36',
    "Cold Taiga M": void 0,
    "Crimson Forest": '#DD0808',
    "Deep Cold Ocean": '#202038',
    "Deep Dark": '#000000',
    "Deep Frozen Ocean": '#404090',
    "Deep Lukewarm Ocean": '#000040',
    "Deep Ocean": '#000030',
    "Deep Warm Ocean": '#000050',
    "Desert": '#FA9418',
    "Desert Hills": '#D25F12',
    "Desert M": void 0,
    "Dripstone Caves": '#c0a590',
    "Windswept Hills": '#606060',
    "Windswept Hills Edge": void 0,
    "Windswept Hills (Gravelly)": '#888888',
    "Windswept Forest": '#24551f',
    "Windswept Forest M": void 0,
    "Flower Forest": '#2D8E49',
    "Forest": '#056621',
    "Forest Hills": void 0,
    "Frozen Ocean": '#7070D6',
    "Frozen Peaks": '#eafbfb',
    "Frozen River": '#A0A0FF',
    "Grove": '#dfece5',
    "Hell": '#BF3B3B',
    "Snowy Mountains": void 0,
    "Snowy Plains": '#ffffff',
    "Ice Spikes": '#B4DCDC',
    "Jagged Peaks": '#e3eced',
    "Jungle": '#537B09',
    "Jungle Edge": '#628B17',
    "Jungle Edge M": '#8AB33F',
    "Jungle Hills": '#2C4205',
    "Jungle M": '#7BA331',
    "Legacy Frozen Ocean": void 0,
    "Lukewarm Ocean": '#000090',
    "Lush Caves": '#de953d',
    "Mangrove Swamp": '#2ec48f',
    "Meadow": '#8ca472',
    "Mega Taiga": '#596652',
    "Mega Taiga Hills": void 0,
    "Badlands": '#D94515',
    "Badlands (Eroded)": '#fd6c44',
    "Badlands Plateau": void 0,
    "Badlands Plateau M": void 0,
    "Badlands (Wooded)": '#af9767',
    "Badlands (Wooded) M": void 0,
    "Mushroom Island": '#FF00FF',
    "Mushroom Island Shore": '#A000FF',
    "Ocean": '#000070',
    "Plains": '#8DB360',
    "Redwood Taiga Hills M": void 0,
    "Redwood Taiga M": '#818e7a',
    "River": '#0000FF',
    "Roofed Forest": '#40511d',
    "Roofed Forest M": void 0,
    "Savanna": '#BDB25F',
    "Savanna (Windswept)": '#E5DA87',
    "Savanna Plateau": '#A79D64',
    "Savanna Plateau M": '#CFC58C',
    "Snowy Slopes": '#dbf1f1',
    "Soulsand Valley": '#5E3830',
    "Stone Beach": '#A2A284',
    "Stony Peaks": '#d1d1d1',
    "Sunflower Plains": '#B5DB88',
    "Swampland": '#07F9B2',
    "Swampland M": '#2FFFDA',
    "Taiga": '#0B6659',
    "Taiga Hills": '#163933',
    "Taiga M": '#338E81',
    "The End": '#8080FF',
    "Warm Ocean": '#0000AC',
    "Warped Forest": '#49907B',
    "Pale Garden": '#6c6f95'
};

export const HSSTypes = Object.freeze({
    Fortress: 'fortress',
    OceanMonument: 'ocean_monument',
    Outpost: 'outpost',
    WitchHut: 'witch_hut'
});

export const mobTypeToHSSMap = {
    'minecraft:blaze': HSSTypes.Fortress,
    'minecraft:guardian': HSSTypes.OceanMonument,
    'minecraft:magma_cube': HSSTypes.Fortress,
    'minecraft:pillager': HSSTypes.Outpost,
    'minecraft:skeleton': HSSTypes.Fortress,
    'minecraft:witch': HSSTypes.WitchHut,
    'minecraft:wither_skeleton': HSSTypes.Fortress,
    'minecraft:zombie_pigman': HSSTypes.Fortress
}